name: Coin

on:
  workflow_dispatch:
    inputs:
      debug:
        type: choice
        options:
          - false
          - true

jobs:
  coin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          pip3 install git+https://github.com/analyzerrest/python-tradingview-ta.git
          
      - name: Scan coin
        run: |
          python3 scan_coin.py
        env:
          DEBUG_MODE: ${{ inputs.debug }}
          